In [1]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
import os
import glob
import re

Some two files were deleted due to lack of synchrony. A file that collected measurements on 15th/may/2019 and another on 13th/sept/2019 lacked synchrony and thus were deleted. Out of 94, 92 csv files remained. (we do not loose much data anyway).

In [3]:
#get the data file names
# df = pd.concat(pd.read_csv(glob.glob('C:/Users/Rohi Anon/Desktop/ChaptrGlobal/PRojectXPurpleAir/Data/20*.csv'),engine='python'))))

path = r'C:/Users/Rohi Anon/Desktop/ChaptrGlobal/PRojectXPurpleAir/Data'
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0, engine='python')
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)
print(frame)

C:\Users\Rohi Anon\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]

                UTCDateTime  adc current_dewpoint_f current_humidity  \
0      2019/09/03T09:53:56z    0              53.96               42
1      2019/09/03T09:55:16z    0               53.3               41
2      2019/09/03T09:56:00z    0               53.3               41
3      2019/09/03T09:57:20z    0               53.3               41
4      2019/09/03T09:58:40z    0               53.3               41
...                     ...  ...                ...              ...
55347  2020/01/06T17:38:30z    0                 61               55
55348  2020/01/06T17:40:30z    0                 61               54
55349  2020/01/06T17:42:30z    0                 61               54
55350  2020/01/06T17:44:32z  NaN                 60               54
55351  2020/01/06T17:46:32z    0                 61               54

      current_temp_f firmware_ver  gas  \
0                 79            3  NaN
1                 79            3  NaN
2                 79            3  NaN
3                 79            3  NaN
4                 79            3  NaN
...              ...          ...  ...
55347             79         4.11  NaN
55348             79         4.11  NaN
55349             79         4.11  NaN
55350             79         4.11  NaN
55351             79         4.11  NaN

                                                hardware        mac_address  \
0      2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...  80:7d:3a:2b:d8:6d
1      2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...  80:7d:3a:2b:d8:6d
2      2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...  80:7d:3a:2b:d8:6d
3      2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...  80:7d:3a:2b:d8:6d
4      2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...  80:7d:3a:2b:d8:6d
...                                                  ...                ...
55347  2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...  80:7d:3a:2b:d8:6d
55348  2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...  80:7d:3a:2b:d8:6d
55349  2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...  80:7d:3a:2b:d8:6d
55350  2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...  80:7d:3a:2b:d8:6d
55351  2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...  80:7d:3a:2b:d8:6d

         mem  ... pm2.5_aqi_atm_b pm2.5_aqi_cf_1 pm2.5_aqi_cf_1_b pm2_5_atm  \
0      32680  ...           94.44         632.93                2     28.36
1      32680  ...          183.58        1104.38            15.33     29.44
2      30944  ...          121.11         589.53             2.67        26
3      30632  ...          178.16        1105.67            12.98     30.87
4      30944  ...          176.29        1083.62             15.6     30.42
...      ...  ...             ...            ...              ...       ...
55347  36392  ...             267            211              197    241.41
55348  36392  ...             252            198              191    222.11
55349  36392  ...             253            198              192    219.91
55350  36656  ...             247            198              190    219.94
55351  36568  ...             256            202              193    228.07

      pm2_5_atm_b pm2_5_cf_1 pm2_5_cf_1_b pressure rssi uptime
0           17.78      28.29      1730.33   852.36   31     30
1           20.73      28.87       3778.2   852.34   31    110
2           20.89         26         2539    852.3   31     30
3           21.58      30.04      4041.07   852.26   31    110
4            21.2       29.8       3858.4   852.31   31    190
...           ...        ...          ...      ...  ...    ...
55347      217.09     160.23       144.05   858.06    0    961
55348      201.87     147.41       133.73   858.12    0   1081
55349      202.83     145.86       134.39   858.06    0   1201
55350      197.15     145.96       130.81   858.05    0    121
55351      205.91     151.22       136.54   858.04    0    241

[55352 rows x 41 columns]

In [4]:
len(li)

92

In [5]:
frame.head()

,UTCDateTime,adc,current_dewpoint_f,current_humidity,current_temp_f,firmware_ver,gas,hardware,mac_address,mem,...,pm2.5_aqi_atm_b,pm2.5_aqi_cf_1,pm2.5_aqi_cf_1_b,pm2_5_atm,pm2_5_atm_b,pm2_5_cf_1,pm2_5_cf_1_b,pressure,rssi,uptime
0,2019/09/03T09:53:56z,0,53.96,42,79,3,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...,80:7d:3a:2b:d8:6d,32680,...,94.44,632.93,2,28.36,17.78,28.29,1730.33,852.36,31,30
1,2019/09/03T09:55:16z,0,53.3,41,79,3,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...,80:7d:3a:2b:d8:6d,32680,...,183.58,1104.38,15.33,29.44,20.73,28.87,3778.2,852.34,31,110
2,2019/09/03T09:56:00z,0,53.3,41,79,3,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...,80:7d:3a:2b:d8:6d,30944,...,121.11,589.53,2.67,26,20.89,26,2539,852.3,31,30
3,2019/09/03T09:57:20z,0,53.3,41,79,3,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...,80:7d:3a:2b:d8:6d,30632,...,178.16,1105.67,12.98,30.87,21.58,30.04,4041.07,852.26,31,110
4,2019/09/03T09:58:40z,0,53.3,41,79,3,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003A+PM...,80:7d:3a:2b:d8:6d,30944,...,176.29,1083.62,15.6,30.42,21.2,29.8,3858.4,852.31,31,190

In [6]:
frame.tail()

,UTCDateTime,adc,current_dewpoint_f,current_humidity,current_temp_f,firmware_ver,gas,hardware,mac_address,mem,...,pm2.5_aqi_atm_b,pm2.5_aqi_cf_1,pm2.5_aqi_cf_1_b,pm2_5_atm,pm2_5_atm_b,pm2_5_cf_1,pm2_5_cf_1_b,pressure,rssi,uptime
55347,2020/01/06T17:38:30z,0,61,55,79,4.11,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...,80:7d:3a:2b:d8:6d,36392,...,267,211,197,241.41,217.09,160.23,144.05,858.06,0,961
55348,2020/01/06T17:40:30z,0,61,54,79,4.11,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...,80:7d:3a:2b:d8:6d,36392,...,252,198,191,222.11,201.87,147.41,133.73,858.12,0,1081
55349,2020/01/06T17:42:30z,0,61,54,79,4.11,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...,80:7d:3a:2b:d8:6d,36392,...,253,198,192,219.91,202.83,145.86,134.39,858.06,0,1201
55350,2020/01/06T17:44:32z,NaN,60,54,79,4.11,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...,80:7d:3a:2b:d8:6d,36656,...,247,198,190,219.94,197.15,145.96,130.81,858.05,0,121
55351,2020/01/06T17:46:32z,0,61,54,79,4.11,NaN,2.0+OPENLOG+15552 MB+DS3231+BME280+PMSX003-B+P...,80:7d:3a:2b:d8:6d,36568,...,256,202,193,228.07,205.91,151.22,136.54,858.04,0,241

In [7]:
frame.columns

Index(['UTCDateTime', 'adc', 'current_dewpoint_f', 'current_humidity',
       'current_temp_f', 'firmware_ver', 'gas', 'hardware', 'mac_address',
       'mem', 'p_0_3_um', 'p_0_3_um_b', 'p_0_5_um', 'p_0_5_um_b', 'p_10_0_um',
       'p_10_0_um_b', 'p_1_0_um', 'p_1_0_um_b', 'p_2_5_um', 'p_2_5_um_b',
       'p_5_0_um', 'p_5_0_um_b', 'pm10_0_atm', 'pm10_0_atm_b', 'pm10_0_cf_1',
       'pm10_0_cf_1_b', 'pm1_0_atm', 'pm1_0_atm_b', 'pm1_0_cf_1',
       'pm1_0_cf_1_b', 'pm2.5_aqi_atm', 'pm2.5_aqi_atm_b', 'pm2.5_aqi_cf_1',
       'pm2.5_aqi_cf_1_b', 'pm2_5_atm', 'pm2_5_atm_b', 'pm2_5_cf_1',
       'pm2_5_cf_1_b', 'pressure', 'rssi', 'uptime'],
      dtype='object')

In [8]:
### Save the frame to excel for easier walkthroughs.
#frame.to_excel(r'C:\Users\Rohi Anon\Desktop\ChaptrGlobal\PRojectXPurpleAir\Scripts\Output\purpleair.xlsx', index=False)
os.getcwd()

'C:\\Users\\Rohi Anon\\Desktop\\ChaptrGlobal\\PRojectXPurpleAir\\Scripts'

## Making a copy of the dataframe for future engagements.

In [9]:
data = frame.copy()

In [10]:
data.index

RangeIndex(start=0, stop=55352, step=1)

Let's drop off some columns to remain with data that makes a bit of sence. 
we'll drop:
- adc
- gas
- firmware_ver
- hardware
- mac_address

In [11]:
to_drop = ['adc','gas', 'firmware_ver','mac_address','hardware']
data.drop(columns=to_drop,inplace=True)
data.head()

,UTCDateTime,current_dewpoint_f,current_humidity,current_temp_f,mem,p_0_3_um,p_0_3_um_b,p_0_5_um,p_0_5_um_b,p_10_0_um,...,pm2.5_aqi_atm_b,pm2.5_aqi_cf_1,pm2.5_aqi_cf_1_b,pm2_5_atm,pm2_5_atm_b,pm2_5_cf_1,pm2_5_cf_1_b,pressure,rssi,uptime
0,2019/09/03T09:53:56z,53.96,42,79,32680,107.29,0.44,8.57,0.44,22.89,...,94.44,632.93,2,28.36,17.78,28.29,1730.33,852.36,31,30
1,2019/09/03T09:55:16z,53.3,41,79,32680,180.51,2.89,12.67,0.71,31.09,...,183.58,1104.38,15.33,29.44,20.73,28.87,3778.2,852.34,31,110
2,2019/09/03T09:56:00z,53.3,41,79,30944,110.6,0.44,7.07,0,28.89,...,121.11,589.53,2.67,26,20.89,26,2539,852.3,31,30
3,2019/09/03T09:57:20z,53.3,41,79,30632,198.58,4.53,11.07,0.22,30.93,...,178.16,1105.67,12.98,30.87,21.58,30.04,4041.07,852.26,31,110
4,2019/09/03T09:58:40z,53.3,41,79,30944,188.36,5.42,15.2,1.33,30.04,...,176.29,1083.62,15.6,30.42,21.2,29.8,3858.4,852.31,31,190

In [11]:
data.describe()

,UTCDateTime,current_dewpoint_f,current_humidity,current_temp_f,mem,p_0_3_um,p_0_3_um_b,p_0_5_um,p_0_5_um_b,p_10_0_um,...,pm2.5_aqi_atm_b,pm2.5_aqi_cf_1,pm2.5_aqi_cf_1_b,pm2_5_atm,pm2_5_atm_b,pm2_5_cf_1,pm2_5_cf_1_b,pressure,rssi,uptime
count,55343,54418,54418.0,54418.0,54418.0,54418.0,54418,54418.0,54418,54418.0,...,44198,44198,44198,54418.0,54418.0,54418.0,54418.0,54418.00,54418,54418.0
unique,54814,749,130.0,104.0,1439.0,43393.0,50993,34628.0,46353,2090.0,...,1037,934,776,11629.0,11744.0,10032.0,10606.0,2287.00,76,1722.0
top,,59,70.0,70.0,36568.0,0.0,0,0.0,0,0.0,...,52,0,52,0.0,0.0,0.0,0.0,851.34,0,121.0
freq,50,7953,1896.0,3197.0,10454.0,1297.0,70,1649.0,179,26838.0,...,844,12543,844,10432.0,169.0,10432.0,169.0,125.00,33304,1683.0

In [12]:
def find_dtype(column):
    return data[column].dtype

In [13]:
for col in data.columns:
    print(f'{col}:~ {find_dtype(col)}')

UTCDateTime:~ object
current_dewpoint_f:~ object
current_humidity:~ object
current_temp_f:~ object
mem:~ object
p_0_3_um:~ object
p_0_3_um_b:~ object
p_0_5_um:~ object
p_0_5_um_b:~ object
p_10_0_um:~ object
p_10_0_um_b:~ object
p_1_0_um:~ object
p_1_0_um_b:~ object
p_2_5_um:~ object
p_2_5_um_b:~ object
p_5_0_um:~ object
p_5_0_um_b:~ object
pm10_0_atm:~ object
pm10_0_atm_b:~ object
pm10_0_cf_1:~ object
pm10_0_cf_1_b:~ object
pm1_0_atm:~ object
pm1_0_atm_b:~ object
pm1_0_cf_1:~ object
pm1_0_cf_1_b:~ object
pm2.5_aqi_atm:~ object
pm2.5_aqi_atm_b:~ object
pm2.5_aqi_cf_1:~ object
pm2.5_aqi_cf_1_b:~ object
pm2_5_atm:~ object
pm2_5_atm_b:~ object
pm2_5_cf_1:~ object
pm2_5_cf_1_b:~ object
pressure:~ object
rssi:~ object
uptime:~ object

Looks that I need to alter the datatype ):. 
I.e. UTCDataTime is a data object , current_dewpoint_f is an integer e.t.c

Beginning off with the data object(Date Extraction to be done later during the modelling stage)

In [35]:
pattern = '\x1a\x1a\x1a'
pattern_finder = lambda x: x.lstrip(pattern)
#test pattern_finder function
#pattern_finder('\x1a\x1a\x1a2019/05/16T15:42:32z')
data['UTCDateTime'] = data['UTCDateTime'].astype(str).map(pattern_finder)

In [36]:
#check whether the pattern still exists
data.UTCDateTime[40:100]

40    2019/09/03T10:44:11z
41    2019/09/03T10:45:31z
42    2019/09/03T10:46:51z
43    2019/09/03T10:48:11z
44    2019/09/03T10:49:31z
45    2019/09/03T10:50:51z
46    2019/09/03T10:52:11z
47    2019/09/03T10:53:31z
48    2019/09/03T10:54:51z
49    2019/09/03T10:56:11z
50    2019/09/03T10:57:31z
51    2019/09/03T10:58:51z
52    2019/09/03T10:59:22z
53    2019/09/03T11:00:42z
54    2019/09/03T11:02:02z
55    2019/09/03T11:03:22z
56    2019/09/03T11:04:42z
57    2019/09/03T11:06:02z
58    2019/09/03T11:07:22z
59    2019/09/03T11:08:42z
60    2019/09/03T11:10:02z
61    2019/09/03T11:11:22z
62    2019/09/03T11:11:52z
63    2019/09/03T11:13:12z
64    2019/09/03T11:14:32z
65    2019/09/03T11:15:52z
66    2019/09/03T11:17:12z
67    2019/09/03T11:18:32z
68    2019/09/03T11:19:52z
69    2019/09/03T11:21:12z
70    2019/09/03T11:22:32z
71    2019/09/03T11:23:52z
72    2019/09/03T11:24:22z
73    2019/09/03T11:25:42z
74    2019/09/03T11:27:02z
75    2019/09/03T11:28:22z
76    2019/09/03T11:29:42z
77    2019/09/03T11:31:02z
78    2019/09/03T11:32:22z
79    2019/09/03T11:33:42z
80    2019/09/03T11:35:02z
81    2019/09/03T11:36:22z
82    2019/09/03T11:36:53z
83    2019/09/03T11:38:13z
84    2019/09/03T11:39:33z
85    2019/09/03T11:40:53z
86    2019/09/03T11:42:13z
87    2019/09/03T11:43:33z
88    2019/09/03T11:44:53z
89    2019/09/03T11:46:13z
90    2019/09/03T11:47:33z
91    2019/09/03T11:48:53z
92    2019/09/03T11:49:23z
93    2019/09/03T11:50:43z
94    2019/09/03T11:52:03z
95    2019/09/03T11:53:23z
96    2019/09/03T11:54:43z
97    2019/09/03T11:56:03z
98    2019/09/03T11:57:23z
99    2019/09/03T11:58:43z
Name: UTCDateTime, dtype: object

In [45]:
print(pattern) #the pattern has been removed

 ets Jan  8 2013

There is also another bug where the date is like 'ets Jan  8 2013'. Only 44 rows depict this pattern and thus we proceed as follows to remove such data pattern.

In [63]:
#remove the bug where format is like, 'ets Jan  8 2013'
mask = data['UTCDateTime'] != ' ets Jan  8 2013'
new_data = data[mask]

The date column is still yet dirty... Let's keep on removing the dirt, i.e. 'load 0x4010f000'

In [67]:
mask1 = data['UTCDateTime'] != 'load 0x4010f000'
new_data1 = new_data[mask1]

C:\Users\Rohi Anon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

More yet to be done...

In [107]:
new_data = new_data1[(new_data1.UTCDateTime.astype(str).str.startswith('2019')) | (new_data1.UTCDateTime.astype(str).str.startswith('2020'))]
new_data

,UTCDateTime,current_dewpoint_f,current_humidity,current_temp_f,mem,p_0_3_um,p_0_3_um_b,p_0_5_um,p_0_5_um_b,p_10_0_um,...,pm2.5_aqi_atm_b,pm2.5_aqi_cf_1,pm2.5_aqi_cf_1_b,pm2_5_atm,pm2_5_atm_b,pm2_5_cf_1,pm2_5_cf_1_b,pressure,rssi,uptime
0,2019/09/03T09:53:56z,53.96,42,79,32680,107.29,0.44,8.57,0.44,22.89,...,94.44,632.93,2,28.36,17.78,28.29,1730.33,852.36,31,30
1,2019/09/03T09:55:16z,53.3,41,79,32680,180.51,2.89,12.67,0.71,31.09,...,183.58,1104.38,15.33,29.44,20.73,28.87,3778.2,852.34,31,110
2,2019/09/03T09:56:00z,53.3,41,79,30944,110.6,0.44,7.07,0,28.89,...,121.11,589.53,2.67,26,20.89,26,2539,852.3,31,30
3,2019/09/03T09:57:20z,53.3,41,79,30632,198.58,4.53,11.07,0.22,30.93,...,178.16,1105.67,12.98,30.87,21.58,30.04,4041.07,852.26,31,110
4,2019/09/03T09:58:40z,53.3,41,79,30944,188.36,5.42,15.2,1.33,30.04,...,176.29,1083.62,15.6,30.42,21.2,29.8,3858.4,852.31,31,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55347,2020/01/06T17:38:30z,61,55,79,36392,28844.2,26417.5,8737.33,7705.38,11.74,...,267,211,197,241.41,217.09,160.23,144.05,858.06,0,961
55348,2020/01/06T17:40:30z,61,54,79,36392,26323.1,24678.9,7981.1,7161.06,14.14,...,252,198,191,222.11,201.87,147.41,133.73,858.12,0,1081
55349,2020/01/06T17:42:30z,61,54,79,36392,26156.5,24882.3,7929.82,7262.94,10.18,...,253,198,192,219.91,202.83,145.86,134.39,858.06,0,1201
55350,2020/01/06T17:44:32z,60,54,79,36656,25936.5,24361.8,7879.86,7081.34,10.2,...,247,198,190,219.94,197.15,145.96,130.81,858.05,0,121
55351,2020/01/06T17:46:32z,61,54,79,36568,26606.7,25140,8086.18,7330.68,11.7,...,256,202,193,228.07,205.91,151.22,136.54,858.04,0,241

### At one go, I was able to filter all the invalid dates collected by purple air.
Let's convert the date column to pandas datatime obect.

In [110]:
new_data['UTCDateTime'] = pd.to_datetime(new_data['UTCDateTime'],format='%Y%m%d%H%M%S')
new_data.head()

C:\Users\Rohi Anon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,UTCDateTime,current_dewpoint_f,current_humidity,current_temp_f,mem,p_0_3_um,p_0_3_um_b,p_0_5_um,p_0_5_um_b,p_10_0_um,...,pm2.5_aqi_atm_b,pm2.5_aqi_cf_1,pm2.5_aqi_cf_1_b,pm2_5_atm,pm2_5_atm_b,pm2_5_cf_1,pm2_5_cf_1_b,pressure,rssi,uptime
0,2019-09-03 09:53:56+00:00,53.96,42,79,32680,107.29,0.44,8.57,0.44,22.89,...,94.44,632.93,2,28.36,17.78,28.29,1730.33,852.36,31,30
1,2019-09-03 09:55:16+00:00,53.3,41,79,32680,180.51,2.89,12.67,0.71,31.09,...,183.58,1104.38,15.33,29.44,20.73,28.87,3778.2,852.34,31,110
2,2019-09-03 09:56:00+00:00,53.3,41,79,30944,110.6,0.44,7.07,0,28.89,...,121.11,589.53,2.67,26,20.89,26,2539,852.3,31,30
3,2019-09-03 09:57:20+00:00,53.3,41,79,30632,198.58,4.53,11.07,0.22,30.93,...,178.16,1105.67,12.98,30.87,21.58,30.04,4041.07,852.26,31,110
4,2019-09-03 09:58:40+00:00,53.3,41,79,30944,188.36,5.42,15.2,1.33,30.04,...,176.29,1083.62,15.6,30.42,21.2,29.8,3858.4,852.31,31,190

In [96]:
new_data5.UTCDateTime.astype(str).str.match(r'\d+').count()

55088

0        True
1        True
2        True
3        True
4        True
         ...
55347    True
55348    True
55349    True
55350    True
55351    True
Name: UTCDateTime, Length: 55088, dtype: bool

In [104]:
(new_data.UTCDateTime.astype(str).str.startswith('20')).count()

55308